# Generated by Django 2.2.23 on 2021-05-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name_ru', models.CharField(max_length=255, verbose_name='Имя продукта')),
                ('description_ru', models.CharField(max_length=1000, verbose_name='Описания продукта')),
                ('price_rub', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Цена')),
                ('product_image', models.ImageField(upload_to='product_images', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
