# Generated by Django 2.2.23 on 2021-05-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(verbose_name='Описания продукта'),
        ),
    ]
