# Generated by Django 2.2.23 on 2021-05-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_auto_20210525_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
    ]
