# Generated by Django 2.2.23 on 2021-05-28 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_auto_20210525_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, verbose_name='Эл. почта')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('delivery_method', models.PositiveSmallIntegerField(choices=[(1, 'Самовывоз'), (2, 'Доставка по Москве - 300 руб.'), (3, 'Доставка за МКАД - 300 руб. + 40 руб/км.')], verbose_name='Доставка')),
                ('address', models.CharField(max_length=2000, verbose_name='Адрес')),
                ('comment', models.TextField(verbose_name='Коментарий')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.Product', verbose_name='Продукты')),
            ],
        ),
    ]
