# Generated by Django 2.2.23 on 2021-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_auto_20210528_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytext',
            name='text_az',
            field=models.TextField(blank=True, null=True, verbose_name='Доставка (az)'),
        ),
        migrations.AddField(
            model_name='deliverytext',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Доставка (en)'),
        ),
        migrations.AddField(
            model_name='minimalordertext',
            name='text_az',
            field=models.TextField(blank=True, null=True, verbose_name='Минимальный заказ (ru)'),
        ),
        migrations.AddField(
            model_name='minimalordertext',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Минимальный заказ (en)'),
        ),
        migrations.AddField(
            model_name='paymenttext',
            name='text_az',
            field=models.TextField(blank=True, null=True, verbose_name='Оплата (az)'),
        ),
        migrations.AddField(
            model_name='paymenttext',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Оплата (en)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_az',
            field=models.TextField(blank=True, null=True, verbose_name='Описания продукта (az)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описания продукта (en)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя продукта (az)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя продукта (en)'),
        ),
    ]
