# Generated by Django 2.2.23 on 2021-05-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitesaddress',
            options={'ordering': ('-pk',), 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='requisitesbank',
            options={'ordering': ('-pk',), 'verbose_name': 'Банковские реквизиты', 'verbose_name_plural': 'Банковские реквизиты'},
        ),
        migrations.AlterModelOptions(
            name='requisitescompanyname',
            options={'ordering': ('-pk',), 'verbose_name': 'Наименование организации', 'verbose_name_plural': 'Наименование организации'},
        ),
        migrations.AlterModelOptions(
            name='requisitesemail',
            options={'ordering': ('-pk',), 'verbose_name': 'Электронная почта', 'verbose_name_plural': 'Электронные почты'},
        ),
        migrations.AlterModelOptions(
            name='requisitesinn_kpp',
            options={'ordering': ('-pk',), 'verbose_name': 'ИНН / КПП', 'verbose_name_plural': 'ИНН / КПП'},
        ),
        migrations.AlterModelOptions(
            name='requisitesphone',
            options={'ordering': ('-pk',), 'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterModelOptions(
            name='sentmessage',
            options={'ordering': ('-sent_at',), 'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщении'},
        ),
    ]
