# Generated by Django 2.2.23 on 2021-06-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0002_auto_20210528_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitesaddress',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='requisitesbank',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='requisitescompanyname',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='requisitesemail',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='requisitesinn_kpp',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='requisitesphone',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='requisitesaddress',
            name='title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес (az)'),
        ),
        migrations.AddField(
            model_name='requisitesaddress',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес (en)'),
        ),
        migrations.AddField(
            model_name='requisitesbank',
            name='title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Банковские реквизиты (az)'),
        ),
        migrations.AddField(
            model_name='requisitesbank',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Банковские реквизиты (en)'),
        ),
        migrations.AddField(
            model_name='requisitescompanyname',
            name='title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование организации (az)'),
        ),
        migrations.AddField(
            model_name='requisitescompanyname',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование организации (en)'),
        ),
        migrations.AddField(
            model_name='requisitesemail',
            name='title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Электронная почта (az)'),
        ),
        migrations.AddField(
            model_name='requisitesemail',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Электронная почта (en)'),
        ),
        migrations.AddField(
            model_name='requisitesinn_kpp',
            name='title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН / КПП (az)'),
        ),
        migrations.AddField(
            model_name='requisitesinn_kpp',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН / КПП (en)'),
        ),
        migrations.AddField(
            model_name='requisitesphone',
            name='title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон (az)'),
        ),
        migrations.AddField(
            model_name='requisitesphone',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон (en)'),
        ),
    ]
